<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Url;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Archiver\Zip;
use Drupal\Core\Archiver\ArchiverException;

/**
 * Implements hook_help().
 */
function dfg_3dviewer_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.wisski_iip_image':
      return '<p>' . t('This is the WissKI module for the integration ' .
        'of IIP (https://iipimage.sourceforge.io/).') . '</p>';
  }
}

/**
* Implements hook_file_validate().
 */
function dfg_3dviewer_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
	#\Drupal::messenger()->addMessage(serialize($entity));
	if($entity->bundle() == "bd3d7baa74856d141bcff7b4193fa128") {
		$file_info = $entity->fbf95bddee5160d515b982b3fd2e05f7->getValue();
		$file_id = $file_info[0]['target_id'];
		$file = \Drupal\file\Entity\File::load($file_id);
		$fileName = $file->getFilename();
		#$entity->set('fa554b216188fd7c52502e8e17509f9d', $fileName);
		#$entity->set('fa554b216188fd7c52502e8e17509f9d', array("en" => array(array("target_id" => $fileName))));
		$file_url = \Drupal::service('file_url_generator')->generate($file->getFileUri());
		$path = str_replace($fileName, "views/" . $fileName, $file_url->toString());
		$base = \Drupal::request()->getSchemeAndHttpHost();
		if (file_exists($base . $path . "_side45.png"))
			$entity->set('f7061d026b2c53e34096e35831b841cd', array($base . $path . "_side45.png", $base . $path . "_side0.png", $base . $path . "_side90.png", $base . $path . "_side135.png", $base . $path . "_side180.png", $base . $path . "_side225.png", $base . $path . "_side270.png", $base . $path . "_side315.png", $base . $path . "_top.png"));
		
		/*\Drupal::messenger()->addMessage($file_url->toString());
		\Drupal::messenger()->addMessage($fileName);
		\Drupal::messenger()->addMessage($path);*/
	}
	#$file = $entity->fbda64e9ba217e59e5fc5f99244f4821;
	//$compression = $entity->field_3d_compression_level;
	//\Drupal::messenger()->addMessage(serialize($entity), 'status');
	if ($entity->bundle() == "file") {
		$file = $entity->toArray();
		$realpath = \Drupal::service('file_system')->realpath($file['uri'][0]['value']);
		$parts = pathinfo($realpath);
		$extension = strtoupper($parts['extension']);
		#\Drupal::messenger()->addMessage(serialize($parts), 'status');
		#\Drupal::messenger()->addMessage('/var/www/html/3drepository/modules/dfg_3dviewer/scripts/convert.sh -b true -i ' . $realpath . ' -f true', 'status');
		if ($extension != 'ZIP' && $extension != 'RAR' && $extension != 'TAR' && $extension != 'GZ' && $extension != 'XZ') {
			$output = shell_exec ('/var/www/html/3drepository/modules/dfg_3dviewer/scripts/convert.sh -c true -l 3 -b true -i "' . "$realpath" . '" -f true');
		}
		else {
			try {
				$extractPath = $parts['dirname'] . "/" . $parts['filename'] . "_" . $extension . "/";
				if ($extension == 'ZIP') {
					$zip = new Zip($realpath);
					$zip->extract($extractPath);
					$zip->remove($realpath);
					$archiveFiles = scandir ($extractPath);
					foreach ($archiveFiles as $zipFile) {
						$partsZip = pathinfo($zipFile);					
						switch (strtolower($partsZip["extension"])) {
							case "obj":
							case "fbx":
							case "ply":
							case "dae":
							case "abc":
							case "blend":
							case "stl":
							case "wrl":
							case "x3d":
							case "ifc":
							case "glb":
							case "gltf":
								#\Drupal::messenger()->addMessage(serialize($extractPath . $zipFile . $parts['filename']), 'status');
								$output = shell_exec ('/var/www/html/3drepository/modules/dfg_3dviewer/scripts/convert.sh -c true -l 3 -b true -i "' . $extractPath . $zipFile . '" -o "' . $extractPath . '" -f true');
								
							break;
						}
					}
				}
				elseif ($extension == 'RAR') {
					$output = shell_exec('/var/www/html/3drepository/modules/dfg_3dviewer/scripts/uncompress.sh -t rar -i "' . $realpath . '" -o "' . $extractPath . '" -n "' . $parts['filename'] . '"');
				}
				elseif ($extension == 'TAR' || $extension == 'GZ' ) {
					$output = shell_exec('/var/www/html/3drepository/modules/dfg_3dviewer/scripts/uncompress.sh -t tar -i "' . $realpath . '" -o "' . $extractPath . '" -n "' . $parts['filename'] . '"');
				}
				elseif ($extension == 'XZ') {
					$output = shell_exec('/var/www/html/3drepository/modules/dfg_3dviewer/scripts/uncompress.sh -t xz -i "' . $realpath . '" -o "' . $extractPath . '" -n "' . $parts['filename'] . '"');
				}
				//\Drupal::messenger()->addMessage("Decompressed files: " . serialize($zip->listContents()), 'status');
			}
			catch (ArchiverException $exception) {
				\Drupal::messenger()->addMessage(serialize($exception), 'status');
			}			
		}
		\Drupal::messenger()->addMessage($output, 'status');
	}
}