name: Build and release dist

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Build dist
        run: npm run build:dist ""

      - name: Pack dist
        run: node ./scripts/pack-dist.js

      - name: Create release and upload dist zip
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ./dfg_3dviewer-dist.zip
